{{- if .Values.backupScripts.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "k8s-backup-manager.fullname" . }}-scripts
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-backup-manager.labels" . | nindent 4 }}
data:
  {{- range $name, $content := .Values.backupScripts.scripts }}
  {{ $name }}-backup.sh: |
    {{ $content | nindent 4 }}
  {{- end }}
{{- end }}
